//
//  Language.swift
//  EduSphere
//
//  Created by Mingchung Xia on 2023-09-16.
//

import Foundation

struct Language: Identifiable {
    let id = UUID()
}

extension Language {
    static let languages: [String] = {
        ["afrikaans",
         "albanian",
         "amharic",
         "arabic",
         "armenian",
         "azerbaijani",
         "basque",
         "belarusian",
         "bengali",
         "bosnian",
         "bulgarian",
         "catalan",
         "cebuano",
         "chichewa",
         "chinese (simplified)",
         "chinese (traditional)",
         "corsican", "croatian",
         "czech",
         "danish",
         "dutch",
         "english",
         "esperanto",
         "estonian",
         "filipino",
         "finnish",
         "french",
         "frisian",
         "galician",
         "georgian",
         "german",
         "greek",
         "gujarati",
         "haitian creole",
         "hausa",
         "hawaiian",
         "hebrew",
         "hindi",
         "hmong",
         "hungarian",
         "icelandic",
         "igbo",
         "indonesian",
         "irish",
         "italian",
         "japanese",
         "javanese",
         "kannada",
         "kazakh",
         "khmer",
         "korean",
         "kurdish (kurmanji)",
         "kyrgyz",
         "lao",
         "latin",
         "latvian",
         "lithuanian",
         "luxembourgish",
         "macedonian",
         "malagasy",
         "malay",
         "malayalam",
         "maltese",
         "maori",
         "marathi",
         "mongolian",
         "myanmar (burmese)",
         "nepali",
         "norwegian",
         "odia",
         "pashto",
         "persian",
         "polish",
         "portuguese",
         "punjabi",
         "romanian", 
         "russian",
         "samoan",
         "scots gaelic",
         "serbian",
         "sesotho",
         "shona",
         "sindhi",
         "sinhala",
         "slovak",
         "slovenian",
         "somali",
         "spanish",
         "sundanese",
         "swahili",
         "swedish",
         "tajik",
         "tamil",
         "telugu",
         "thai",
         "turkish",
         "ukrainian",
         "urdu",
         "uyghur",
         "uzbek",
         "vietnamese",
         "welsh",
         "xhosa",
         "yiddish",
         "yoruba",
         "zulu"]
    }()
}
